In [1]:
import numpy as np
import time
def define_start(which, N):
    path='/Users/kypotter/Desktop/School/Artificial Intelligence/SlidingBlocks/examples'
    with open(f'{path}/{which}') as f:
        lines = f.readlines()
        lines=lines[1:(N+1)]
    list_of_lists=[]
    init=[]
    for line in lines:
        s = line.strip()
        line_list = s.split()
        for i in line_list:
            init.append(int(i))
    init=np.reshape(init, (N, N))
    return init

In [2]:
class Game:
    def __init__(self, board, parent=None, path=0, N=3, move=None): 
        self.parent = parent
        self.board=board
        self.move=move
        self.path = path
        self.N=N
        if self.N==3:
            self.goal=[[0,1,2],[3,4,5],[6,7,8]]
        if self.N==4:
            self.goal=[[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]]
        
    def up(self):
            curr=self.board
            for i in range(len(curr)):
                  for j in range(len(curr)):
                        if (curr[i][j])==0:
                            zero=[i,j]
            if zero[0]==0: # if in top row, can't move up
                return
            else:
                slide_up=self.board[zero[0]-1, zero[1]]
                new_board=self.board.copy()
                # Update board
                new_board[zero[0],zero[1]]=slide_up
                new_board[zero[0]-1, zero[1]]=0
                return new_board, slide_up
    def left(self):
            curr=self.board
            for i in range(len(curr)):
                  for j in range(len(curr)):
                        if (curr[i][j])==0:
                            zero=[i,j]
            if zero[1]==0: # if zero in first column, can't move left
                return 
            else:
                slide_left=self.board[zero[0], zero[1]-1]
                new_board=self.board.copy()
                # Update board
                new_board[zero[0],zero[1]]=slide_left # move zero left
                new_board[zero[0], zero[1]-1]=0
                return new_board, slide_left
    def down(self):
            curr=self.board
            for i in range(len(curr)):
                  for j in range(len(curr)):
                        if (curr[i][j])==0:
                            zero=[i,j]
            if zero[0]==(self.N-1): # if on bottom row, can't move down
                return 
            else:
                new_board=self.board.copy()
                slide_down=self.board[zero[0]+1, zero[1]] # move 0 down
                # Update board
                new_board[zero[0],zero[1]]=slide_down
                new_board[zero[0]+1, zero[1]]=0
                return new_board, slide_down
    
    def right(self):
            curr=self.board
            for i in range(len(curr)):
                  for j in range(len(curr)):
                        if (curr[i][j])==0:
                            zero=[i,j]
            if zero[1]==(self.N-1): # if zero in last column, can't move right
                return
            else:
                slide_right=self.board[zero[0], zero[1]+1] # move 0 right
                new_board=self.board.copy()
                # Update board
                new_board[zero[0],zero[1]]=slide_right
                new_board[zero[0], zero[1]+1]=0
                return new_board, slide_right
   
    def bfs(self):
            start= time.time() # Start time
            path=[0] # Set path equal to 0
            visited=set([]) # Create a list for visited
            queue=[self] 
            while queue:
                curr_path=path.pop(0) # current path
                curr=queue.pop(0)  # remove first object in the queue set curr equal to
                store=(curr.board.reshape(1,self.N**2)) # 1xN^2 for faster times
                visited.add(tuple(store[0])) # tuple for faster times
                if np.array_equal(curr.board, self.goal): # if board is equal to goal
                    curr.path_taken() # return the path taken
                    end=time.time() 
                    return (f'Time:{end-start}')
                else:
                    if curr.up(): # if can move up
                        new_board, slide_up = curr.up() 
                        store=new_board.reshape(1, self.N**2) 
                        if tuple(store[0]) not in visited:# if haven't visited
                            curr.slide_up=Game(board=new_board,
                                               parent=curr, 
                                               path=curr_path+slide_up,
                                               N=self.N, 
                                               move='up')
                            queue.append(curr.slide_up)
                            path.append(curr_path+slide_up)
                    if curr.left(): # if can move left
                        new_board,slide_left=curr.left()
                        store=new_board.reshape(1, self.N**2)
                        if tuple(store[0]) not in visited: # if haven't visited
                            curr.slide_left=Game(board=new_board,
                                                 parent=curr,
                                                 move='left',
                                                 path=curr_path+slide_left,
                                                 N=self.N)
                            queue.append(curr.slide_left)
                            path.append(curr_path+slide_left)
                    
                    if curr.down(): # if can move down
                        new_board,slide_down=curr.down()
                        store=new_board.reshape(1, self.N**2)
                        if tuple(store[0]) not in visited: # if haven't visited
                            curr.slide_down=Game(board=new_board,
                                                 parent=curr,
                                                 move='down',
                                                 path=curr_path+slide_down,
                                                 N=self.N)
                            queue.append(curr.slide_down)
                            path.append(curr_path+slide_down)
                    
                    if curr.right(): # if can move right
                        new_board,slide_right=curr.right()
                        store=new_board.reshape(1, self.N**2)
                        if tuple(store[0]) not in visited: # if haven't visited
                            curr.slide_right=Game(board=new_board,
                                                  parent=curr,
                                                  move='right',
                                                  path=curr_path+slide_right,
                                                  N=self.N)
                            queue.append(curr.slide_right)
                            path.append(curr_path+slide_right)
                    
    
    def AStar(self):
        start = time.time()
        queue = [(self,0)]
        path_queue = [0] 
        visited = set([])
        
        while queue:
            curr = queue.pop(0)[0] # remove first object in the queue stores as curr
            curr_path = path_queue.pop(0) 
            visited.add(tuple(curr.board.reshape(1,self.N**2)[0]))
            
            if np.array_equal(curr.board, self.goal): # if board equals goal board
                curr.path_taken() # return path taken
                end=time.time()
                return(f'Time:{end-start}')
            
            else:     
                if curr.up(): # if can move up
                    new_board,slide_up = curr.up() # store values of moving up
                    store=new_board.reshape(1, self.N**2) # reshape for efficiency
                    if tuple(store[0]) not in visited: # if haven't visited
                        path=curr_path+slide_up+self.manhattan(new_board) # path cost including heuristic
                        curr.slide_up = Game(board=new_board,parent=curr, move='up', path=(curr_path+slide_up) , N=self.N) 
                        queue.append((curr.slide_up, path)) # slide up and path cost
                        path_queue.append(curr_path+slide_up) 
                if curr.down(): # if can move down
                    new_board,slide_down = curr.down()
                    store=new_board.reshape(1, self.N**2)
                    if tuple(store[0]) not in visited:# if haven't visited
                        path= curr_path+slide_down+self.manhattan(new_board)
                        curr.slide_down = Game(board=new_board,parent=curr, move='down',path=(curr_path+slide_down) ,N=self.N)
                        queue.append((curr.slide_down, path))
                        path_queue.append(curr_path+slide_down)
               
                if curr.left(): # if can move left
                    new_board,slide_left = curr.left()
                    store=new_board.reshape(1, self.N**2)
                    if tuple(store[0]) not in visited: # if haven't visited
                        path=curr_path+slide_left+self.manhattan(new_board)
                        curr.slide_left = Game(board=new_board,parent=curr, move='left',path=(curr_path+slide_left) , N=self.N)
                        queue.append((curr.slide_left, path))
                        path_queue.append(curr_path+slide_left)
                    
                if curr.right(): # if can move right
                    new_board,slide_right = curr.right() 
                    store=new_board.reshape(1, self.N**2)
                    if tuple(store[0]) not in visited: # if haven't visited
                        path=curr_path+slide_right+self.manhattan(new_board)
                        curr.slide_right = Game(board=new_board,parent=curr, move='right', path=(curr_path+slide_right),N=self.N)
                        queue.append((curr.slide_right, path))
                        path_queue.append(curr_path+slide_right)
    
    def manhattan(self, new_board):
        return np.abs(self.goal - new_board).sum()
                       
    def path_taken(self):
            states=[self.board]
            moves=[self.move]
            move_num=0
            while self.parent:
                self=self.parent
                states.append(self.board)
                moves.append(self.move)
            while states: 
                print(f'step: {move_num}, move: {moves.pop(-1)}')
                print(states.pop())
                print('------------')
                move_num+=1


# Easy

In [3]:
start=define_start('easy/3x3_1', 3)
play=Game(start)
play.bfs()

step: 0, move: None
[[1 2 5]
 [3 4 8]
 [6 7 0]]
------------
step: 1, move: up
[[1 2 5]
 [3 4 0]
 [6 7 8]]
------------
step: 2, move: up
[[1 2 0]
 [3 4 5]
 [6 7 8]]
------------
step: 3, move: left
[[1 0 2]
 [3 4 5]
 [6 7 8]]
------------
step: 4, move: left
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.005778074264526367'

In [4]:
play.AStar()

step: 0, move: None
[[1 2 5]
 [3 4 8]
 [6 7 0]]
------------
step: 1, move: up
[[1 2 5]
 [3 4 0]
 [6 7 8]]
------------
step: 2, move: up
[[1 2 0]
 [3 4 5]
 [6 7 8]]
------------
step: 3, move: left
[[1 0 2]
 [3 4 5]
 [6 7 8]]
------------
step: 4, move: left
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.010479211807250977'

In [5]:
start=define_start('easy/3x3_2', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[1 0 5]
 [3 2 4]
 [6 7 8]]
------------
step: 1, move: down
[[1 2 5]
 [3 0 4]
 [6 7 8]]
------------
step: 2, move: right
[[1 2 5]
 [3 4 0]
 [6 7 8]]
------------
step: 3, move: up
[[1 2 0]
 [3 4 5]
 [6 7 8]]
------------
step: 4, move: left
[[1 0 2]
 [3 4 5]
 [6 7 8]]
------------
step: 5, move: left
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.014898061752319336'

In [77]:
play.AStar()

step: 0, move: None
[[1 0 5]
 [3 2 4]
 [6 7 8]]
------------
step: 1, move: down
[[1 2 5]
 [3 0 4]
 [6 7 8]]
------------
step: 2, move: right
[[1 2 5]
 [3 4 0]
 [6 7 8]]
------------
step: 3, move: up
[[1 2 0]
 [3 4 5]
 [6 7 8]]
------------
step: 4, move: left
[[1 0 2]
 [3 4 5]
 [6 7 8]]
------------
step: 5, move: left
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.02002406120300293'

In [78]:
start=define_start('easy/3x3_3', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[3 2 5]
 [4 0 1]
 [6 7 8]]
------------
step: 1, move: right
[[3 2 5]
 [4 1 0]
 [6 7 8]]
------------
step: 2, move: up
[[3 2 0]
 [4 1 5]
 [6 7 8]]
------------
step: 3, move: left
[[3 0 2]
 [4 1 5]
 [6 7 8]]
------------
step: 4, move: down
[[3 1 2]
 [4 0 5]
 [6 7 8]]
------------
step: 5, move: left
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 6, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.02182292938232422'

In [79]:
play.AStar()

step: 0, move: None
[[3 2 5]
 [4 0 1]
 [6 7 8]]
------------
step: 1, move: right
[[3 2 5]
 [4 1 0]
 [6 7 8]]
------------
step: 2, move: up
[[3 2 0]
 [4 1 5]
 [6 7 8]]
------------
step: 3, move: left
[[3 0 2]
 [4 1 5]
 [6 7 8]]
------------
step: 4, move: down
[[3 1 2]
 [4 0 5]
 [6 7 8]]
------------
step: 5, move: left
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 6, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.026499032974243164'

In [80]:
start=define_start('easy/3x3_4', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.0005512237548828125'

In [81]:
play.AStar()

step: 0, move: None
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.0006988048553466797'

In [82]:
start=define_start('easy/3x3_5', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[4 3 2]
 [0 1 5]
 [6 7 8]]
------------
step: 1, move: up
[[0 3 2]
 [4 1 5]
 [6 7 8]]
------------
step: 2, move: right
[[3 0 2]
 [4 1 5]
 [6 7 8]]
------------
step: 3, move: down
[[3 1 2]
 [4 0 5]
 [6 7 8]]
------------
step: 4, move: left
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 5, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.011876821517944336'

In [83]:
play.AStar()

step: 0, move: None
[[4 3 2]
 [0 1 5]
 [6 7 8]]
------------
step: 1, move: up
[[0 3 2]
 [4 1 5]
 [6 7 8]]
------------
step: 2, move: right
[[3 0 2]
 [4 1 5]
 [6 7 8]]
------------
step: 3, move: down
[[3 1 2]
 [4 0 5]
 [6 7 8]]
------------
step: 4, move: left
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 5, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.024944782257080078'

In [84]:
start=define_start('easy/3x3_6', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[3 2 5]
 [6 1 0]
 [7 4 8]]
------------
step: 1, move: up
[[3 2 0]
 [6 1 5]
 [7 4 8]]
------------
step: 2, move: left
[[3 0 2]
 [6 1 5]
 [7 4 8]]
------------
step: 3, move: down
[[3 1 2]
 [6 0 5]
 [7 4 8]]
------------
step: 4, move: down
[[3 1 2]
 [6 4 5]
 [7 0 8]]
------------
step: 5, move: left
[[3 1 2]
 [6 4 5]
 [0 7 8]]
------------
step: 6, move: up
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 7, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.019925832748413086'

In [85]:
play.AStar()

step: 0, move: None
[[3 2 5]
 [6 1 0]
 [7 4 8]]
------------
step: 1, move: up
[[3 2 0]
 [6 1 5]
 [7 4 8]]
------------
step: 2, move: left
[[3 0 2]
 [6 1 5]
 [7 4 8]]
------------
step: 3, move: down
[[3 1 2]
 [6 0 5]
 [7 4 8]]
------------
step: 4, move: down
[[3 1 2]
 [6 4 5]
 [7 0 8]]
------------
step: 5, move: left
[[3 1 2]
 [6 4 5]
 [0 7 8]]
------------
step: 6, move: up
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 7, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.0279080867767334'

In [86]:
start=define_start('easy/3x3_7', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[1 4 2]
 [3 5 8]
 [0 6 7]]
------------
step: 1, move: right
[[1 4 2]
 [3 5 8]
 [6 0 7]]
------------
step: 2, move: right
[[1 4 2]
 [3 5 8]
 [6 7 0]]
------------
step: 3, move: up
[[1 4 2]
 [3 5 0]
 [6 7 8]]
------------
step: 4, move: left
[[1 4 2]
 [3 0 5]
 [6 7 8]]
------------
step: 5, move: up
[[1 0 2]
 [3 4 5]
 [6 7 8]]
------------
step: 6, move: left
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.02050614356994629'

In [87]:
play.AStar()

step: 0, move: None
[[1 4 2]
 [3 5 8]
 [0 6 7]]
------------
step: 1, move: right
[[1 4 2]
 [3 5 8]
 [6 0 7]]
------------
step: 2, move: right
[[1 4 2]
 [3 5 8]
 [6 7 0]]
------------
step: 3, move: up
[[1 4 2]
 [3 5 0]
 [6 7 8]]
------------
step: 4, move: left
[[1 4 2]
 [3 0 5]
 [6 7 8]]
------------
step: 5, move: up
[[1 0 2]
 [3 4 5]
 [6 7 8]]
------------
step: 6, move: left
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.021303892135620117'

In [88]:
start=define_start('easy/3x3_8', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[1 4 2]
 [7 0 5]
 [3 6 8]]
------------
step: 1, move: left
[[1 4 2]
 [0 7 5]
 [3 6 8]]
------------
step: 2, move: down
[[1 4 2]
 [3 7 5]
 [0 6 8]]
------------
step: 3, move: right
[[1 4 2]
 [3 7 5]
 [6 0 8]]
------------
step: 4, move: up
[[1 4 2]
 [3 0 5]
 [6 7 8]]
------------
step: 5, move: up
[[1 0 2]
 [3 4 5]
 [6 7 8]]
------------
step: 6, move: left
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.01896500587463379'

In [89]:
play.AStar()

step: 0, move: None
[[1 4 2]
 [7 0 5]
 [3 6 8]]
------------
step: 1, move: left
[[1 4 2]
 [0 7 5]
 [3 6 8]]
------------
step: 2, move: down
[[1 4 2]
 [3 7 5]
 [0 6 8]]
------------
step: 3, move: right
[[1 4 2]
 [3 7 5]
 [6 0 8]]
------------
step: 4, move: up
[[1 4 2]
 [3 0 5]
 [6 7 8]]
------------
step: 5, move: up
[[1 0 2]
 [3 4 5]
 [6 7 8]]
------------
step: 6, move: left
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.027142047882080078'

In [90]:
start=define_start('easy/3x3_9', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[3 1 2]
 [4 7 5]
 [6 0 8]]
------------
step: 1, move: up
[[3 1 2]
 [4 0 5]
 [6 7 8]]
------------
step: 2, move: left
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 3, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.005434989929199219'

In [91]:
play.AStar()

step: 0, move: None
[[3 1 2]
 [4 7 5]
 [6 0 8]]
------------
step: 1, move: up
[[3 1 2]
 [4 0 5]
 [6 7 8]]
------------
step: 2, move: left
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 3, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.008508920669555664'

In [92]:
start=define_start('easy/3x3_10', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[3 0 2]
 [4 1 8]
 [6 5 7]]
------------
step: 1, move: down
[[3 1 2]
 [4 0 8]
 [6 5 7]]
------------
step: 2, move: down
[[3 1 2]
 [4 5 8]
 [6 0 7]]
------------
step: 3, move: right
[[3 1 2]
 [4 5 8]
 [6 7 0]]
------------
step: 4, move: up
[[3 1 2]
 [4 5 0]
 [6 7 8]]
------------
step: 5, move: left
[[3 1 2]
 [4 0 5]
 [6 7 8]]
------------
step: 6, move: left
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 7, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.024857044219970703'

In [93]:
play.AStar()

step: 0, move: None
[[3 0 2]
 [4 1 8]
 [6 5 7]]
------------
step: 1, move: down
[[3 1 2]
 [4 0 8]
 [6 5 7]]
------------
step: 2, move: down
[[3 1 2]
 [4 5 8]
 [6 0 7]]
------------
step: 3, move: right
[[3 1 2]
 [4 5 8]
 [6 7 0]]
------------
step: 4, move: up
[[3 1 2]
 [4 5 0]
 [6 7 8]]
------------
step: 5, move: left
[[3 1 2]
 [4 0 5]
 [6 7 8]]
------------
step: 6, move: left
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 7, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.030282974243164062'

# Moderate

In [96]:
start=define_start('moderate/3x3_1', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[2 6 5]
 [1 3 4]
 [7 8 0]]
------------
step: 1, move: left
[[2 6 5]
 [1 3 4]
 [7 0 8]]
------------
step: 2, move: up
[[2 6 5]
 [1 0 4]
 [7 3 8]]
------------
step: 3, move: up
[[2 0 5]
 [1 6 4]
 [7 3 8]]
------------
step: 4, move: left
[[0 2 5]
 [1 6 4]
 [7 3 8]]
------------
step: 5, move: down
[[1 2 5]
 [0 6 4]
 [7 3 8]]
------------
step: 6, move: right
[[1 2 5]
 [6 0 4]
 [7 3 8]]
------------
step: 7, move: down
[[1 2 5]
 [6 3 4]
 [7 0 8]]
------------
step: 8, move: left
[[1 2 5]
 [6 3 4]
 [0 7 8]]
------------
step: 9, move: up
[[1 2 5]
 [0 3 4]
 [6 7 8]]
------------
step: 10, move: right
[[1 2 5]
 [3 0 4]
 [6 7 8]]
------------
step: 11, move: right
[[1 2 5]
 [3 4 0]
 [6 7 8]]
------------
step: 12, move: up
[[1 2 0]
 [3 4 5]
 [6 7 8]]
------------
step: 13, move: left
[[1 0 2]
 [3 4 5]
 [6 7 8]]
------------
step: 14, move: left
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.2830181121826172'

In [97]:
play.AStar()

step: 0, move: None
[[2 6 5]
 [1 3 4]
 [7 8 0]]
------------
step: 1, move: left
[[2 6 5]
 [1 3 4]
 [7 0 8]]
------------
step: 2, move: up
[[2 6 5]
 [1 0 4]
 [7 3 8]]
------------
step: 3, move: up
[[2 0 5]
 [1 6 4]
 [7 3 8]]
------------
step: 4, move: left
[[0 2 5]
 [1 6 4]
 [7 3 8]]
------------
step: 5, move: down
[[1 2 5]
 [0 6 4]
 [7 3 8]]
------------
step: 6, move: right
[[1 2 5]
 [6 0 4]
 [7 3 8]]
------------
step: 7, move: down
[[1 2 5]
 [6 3 4]
 [7 0 8]]
------------
step: 8, move: left
[[1 2 5]
 [6 3 4]
 [0 7 8]]
------------
step: 9, move: up
[[1 2 5]
 [0 3 4]
 [6 7 8]]
------------
step: 10, move: right
[[1 2 5]
 [3 0 4]
 [6 7 8]]
------------
step: 11, move: right
[[1 2 5]
 [3 4 0]
 [6 7 8]]
------------
step: 12, move: up
[[1 2 0]
 [3 4 5]
 [6 7 8]]
------------
step: 13, move: left
[[1 0 2]
 [3 4 5]
 [6 7 8]]
------------
step: 14, move: left
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.45825695991516113'

In [98]:
start=define_start('moderate/3x3_2', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[3 5 4]
 [2 1 8]
 [6 0 7]]
------------
step: 1, move: right
[[3 5 4]
 [2 1 8]
 [6 7 0]]
------------
step: 2, move: up
[[3 5 4]
 [2 1 0]
 [6 7 8]]
------------
step: 3, move: up
[[3 5 0]
 [2 1 4]
 [6 7 8]]
------------
step: 4, move: left
[[3 0 5]
 [2 1 4]
 [6 7 8]]
------------
step: 5, move: down
[[3 1 5]
 [2 0 4]
 [6 7 8]]
------------
step: 6, move: left
[[3 1 5]
 [0 2 4]
 [6 7 8]]
------------
step: 7, move: up
[[0 1 5]
 [3 2 4]
 [6 7 8]]
------------
step: 8, move: right
[[1 0 5]
 [3 2 4]
 [6 7 8]]
------------
step: 9, move: down
[[1 2 5]
 [3 0 4]
 [6 7 8]]
------------
step: 10, move: right
[[1 2 5]
 [3 4 0]
 [6 7 8]]
------------
step: 11, move: up
[[1 2 0]
 [3 4 5]
 [6 7 8]]
------------
step: 12, move: left
[[1 0 2]
 [3 4 5]
 [6 7 8]]
------------
step: 13, move: left
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.21706795692443848'

In [99]:
play.AStar()

step: 0, move: None
[[3 5 4]
 [2 1 8]
 [6 0 7]]
------------
step: 1, move: right
[[3 5 4]
 [2 1 8]
 [6 7 0]]
------------
step: 2, move: up
[[3 5 4]
 [2 1 0]
 [6 7 8]]
------------
step: 3, move: up
[[3 5 0]
 [2 1 4]
 [6 7 8]]
------------
step: 4, move: left
[[3 0 5]
 [2 1 4]
 [6 7 8]]
------------
step: 5, move: down
[[3 1 5]
 [2 0 4]
 [6 7 8]]
------------
step: 6, move: left
[[3 1 5]
 [0 2 4]
 [6 7 8]]
------------
step: 7, move: up
[[0 1 5]
 [3 2 4]
 [6 7 8]]
------------
step: 8, move: right
[[1 0 5]
 [3 2 4]
 [6 7 8]]
------------
step: 9, move: down
[[1 2 5]
 [3 0 4]
 [6 7 8]]
------------
step: 10, move: right
[[1 2 5]
 [3 4 0]
 [6 7 8]]
------------
step: 11, move: up
[[1 2 0]
 [3 4 5]
 [6 7 8]]
------------
step: 12, move: left
[[1 0 2]
 [3 4 5]
 [6 7 8]]
------------
step: 13, move: left
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.25586771965026855'

In [100]:
start=define_start('moderate/3x3_3', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[7 5 0]
 [2 3 1]
 [4 6 8]]
------------
step: 1, move: left
[[7 0 5]
 [2 3 1]
 [4 6 8]]
------------
step: 2, move: left
[[0 7 5]
 [2 3 1]
 [4 6 8]]
------------
step: 3, move: down
[[2 7 5]
 [0 3 1]
 [4 6 8]]
------------
step: 4, move: right
[[2 7 5]
 [3 0 1]
 [4 6 8]]
------------
step: 5, move: up
[[2 0 5]
 [3 7 1]
 [4 6 8]]
------------
step: 6, move: left
[[0 2 5]
 [3 7 1]
 [4 6 8]]
------------
step: 7, move: down
[[3 2 5]
 [0 7 1]
 [4 6 8]]
------------
step: 8, move: down
[[3 2 5]
 [4 7 1]
 [0 6 8]]
------------
step: 9, move: right
[[3 2 5]
 [4 7 1]
 [6 0 8]]
------------
step: 10, move: up
[[3 2 5]
 [4 0 1]
 [6 7 8]]
------------
step: 11, move: right
[[3 2 5]
 [4 1 0]
 [6 7 8]]
------------
step: 12, move: up
[[3 2 0]
 [4 1 5]
 [6 7 8]]
------------
step: 13, move: left
[[3 0 2]
 [4 1 5]
 [6 7 8]]
------------
step: 14, move: down
[[3 1 2]
 [4 0 5]
 [6 7 8]]
------------
step: 15, move: left
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 16, move: up
[[

'Time:0.539482831954956'

In [101]:
play.AStar()

step: 0, move: None
[[7 5 0]
 [2 3 1]
 [4 6 8]]
------------
step: 1, move: left
[[7 0 5]
 [2 3 1]
 [4 6 8]]
------------
step: 2, move: down
[[7 3 5]
 [2 0 1]
 [4 6 8]]
------------
step: 3, move: left
[[7 3 5]
 [0 2 1]
 [4 6 8]]
------------
step: 4, move: up
[[0 3 5]
 [7 2 1]
 [4 6 8]]
------------
step: 5, move: right
[[3 0 5]
 [7 2 1]
 [4 6 8]]
------------
step: 6, move: down
[[3 2 5]
 [7 0 1]
 [4 6 8]]
------------
step: 7, move: right
[[3 2 5]
 [7 1 0]
 [4 6 8]]
------------
step: 8, move: up
[[3 2 0]
 [7 1 5]
 [4 6 8]]
------------
step: 9, move: left
[[3 0 2]
 [7 1 5]
 [4 6 8]]
------------
step: 10, move: down
[[3 1 2]
 [7 0 5]
 [4 6 8]]
------------
step: 11, move: left
[[3 1 2]
 [0 7 5]
 [4 6 8]]
------------
step: 12, move: down
[[3 1 2]
 [4 7 5]
 [0 6 8]]
------------
step: 13, move: right
[[3 1 2]
 [4 7 5]
 [6 0 8]]
------------
step: 14, move: up
[[3 1 2]
 [4 0 5]
 [6 7 8]]
------------
step: 15, move: left
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 16, move: up
[[

'Time:1.342249870300293'

In [102]:
start=define_start('moderate/3x3_4', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[3 1 2]
 [4 0 8]
 [6 5 7]]
------------
step: 1, move: down
[[3 1 2]
 [4 5 8]
 [6 0 7]]
------------
step: 2, move: right
[[3 1 2]
 [4 5 8]
 [6 7 0]]
------------
step: 3, move: up
[[3 1 2]
 [4 5 0]
 [6 7 8]]
------------
step: 4, move: left
[[3 1 2]
 [4 0 5]
 [6 7 8]]
------------
step: 5, move: left
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 6, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.02442002296447754'

In [103]:
play.AStar()

step: 0, move: None
[[3 1 2]
 [4 0 8]
 [6 5 7]]
------------
step: 1, move: down
[[3 1 2]
 [4 5 8]
 [6 0 7]]
------------
step: 2, move: right
[[3 1 2]
 [4 5 8]
 [6 7 0]]
------------
step: 3, move: up
[[3 1 2]
 [4 5 0]
 [6 7 8]]
------------
step: 4, move: left
[[3 1 2]
 [4 0 5]
 [6 7 8]]
------------
step: 5, move: left
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 6, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.03149008750915527'

In [104]:
start=define_start('moderate/3x3_5', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[3 0 2]
 [4 1 7]
 [6 8 5]]
------------
step: 1, move: down
[[3 1 2]
 [4 0 7]
 [6 8 5]]
------------
step: 2, move: right
[[3 1 2]
 [4 7 0]
 [6 8 5]]
------------
step: 3, move: down
[[3 1 2]
 [4 7 5]
 [6 8 0]]
------------
step: 4, move: left
[[3 1 2]
 [4 7 5]
 [6 0 8]]
------------
step: 5, move: up
[[3 1 2]
 [4 0 5]
 [6 7 8]]
------------
step: 6, move: left
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 7, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.02576899528503418'

In [105]:
play.AStar()

step: 0, move: None
[[3 0 2]
 [4 1 7]
 [6 8 5]]
------------
step: 1, move: down
[[3 1 2]
 [4 0 7]
 [6 8 5]]
------------
step: 2, move: right
[[3 1 2]
 [4 7 0]
 [6 8 5]]
------------
step: 3, move: down
[[3 1 2]
 [4 7 5]
 [6 8 0]]
------------
step: 4, move: left
[[3 1 2]
 [4 7 5]
 [6 0 8]]
------------
step: 5, move: up
[[3 1 2]
 [4 0 5]
 [6 7 8]]
------------
step: 6, move: left
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 7, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.039361000061035156'

In [106]:
start=define_start('moderate/3x3_6', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[6 3 5]
 [2 1 8]
 [7 4 0]]
------------
step: 1, move: up
[[6 3 5]
 [2 1 0]
 [7 4 8]]
------------
step: 2, move: left
[[6 3 5]
 [2 0 1]
 [7 4 8]]
------------
step: 3, move: left
[[6 3 5]
 [0 2 1]
 [7 4 8]]
------------
step: 4, move: up
[[0 3 5]
 [6 2 1]
 [7 4 8]]
------------
step: 5, move: right
[[3 0 5]
 [6 2 1]
 [7 4 8]]
------------
step: 6, move: down
[[3 2 5]
 [6 0 1]
 [7 4 8]]
------------
step: 7, move: right
[[3 2 5]
 [6 1 0]
 [7 4 8]]
------------
step: 8, move: up
[[3 2 0]
 [6 1 5]
 [7 4 8]]
------------
step: 9, move: left
[[3 0 2]
 [6 1 5]
 [7 4 8]]
------------
step: 10, move: down
[[3 1 2]
 [6 0 5]
 [7 4 8]]
------------
step: 11, move: down
[[3 1 2]
 [6 4 5]
 [7 0 8]]
------------
step: 12, move: left
[[3 1 2]
 [6 4 5]
 [0 7 8]]
------------
step: 13, move: up
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 14, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.2552940845489502'

In [107]:
play.AStar()

step: 0, move: None
[[6 3 5]
 [2 1 8]
 [7 4 0]]
------------
step: 1, move: up
[[6 3 5]
 [2 1 0]
 [7 4 8]]
------------
step: 2, move: left
[[6 3 5]
 [2 0 1]
 [7 4 8]]
------------
step: 3, move: left
[[6 3 5]
 [0 2 1]
 [7 4 8]]
------------
step: 4, move: up
[[0 3 5]
 [6 2 1]
 [7 4 8]]
------------
step: 5, move: right
[[3 0 5]
 [6 2 1]
 [7 4 8]]
------------
step: 6, move: down
[[3 2 5]
 [6 0 1]
 [7 4 8]]
------------
step: 7, move: right
[[3 2 5]
 [6 1 0]
 [7 4 8]]
------------
step: 8, move: up
[[3 2 0]
 [6 1 5]
 [7 4 8]]
------------
step: 9, move: left
[[3 0 2]
 [6 1 5]
 [7 4 8]]
------------
step: 10, move: down
[[3 1 2]
 [6 0 5]
 [7 4 8]]
------------
step: 11, move: down
[[3 1 2]
 [6 4 5]
 [7 0 8]]
------------
step: 12, move: left
[[3 1 2]
 [6 4 5]
 [0 7 8]]
------------
step: 13, move: up
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 14, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.4372522830963135'

In [108]:
start=define_start('moderate/3x3_7', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[0 3 1]
 [4 5 2]
 [6 7 8]]
------------
step: 1, move: right
[[3 0 1]
 [4 5 2]
 [6 7 8]]
------------
step: 2, move: right
[[3 1 0]
 [4 5 2]
 [6 7 8]]
------------
step: 3, move: down
[[3 1 2]
 [4 5 0]
 [6 7 8]]
------------
step: 4, move: left
[[3 1 2]
 [4 0 5]
 [6 7 8]]
------------
step: 5, move: left
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 6, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.021431684494018555'

In [109]:
play.AStar()

step: 0, move: None
[[0 3 1]
 [4 5 2]
 [6 7 8]]
------------
step: 1, move: right
[[3 0 1]
 [4 5 2]
 [6 7 8]]
------------
step: 2, move: right
[[3 1 0]
 [4 5 2]
 [6 7 8]]
------------
step: 3, move: down
[[3 1 2]
 [4 5 0]
 [6 7 8]]
------------
step: 4, move: left
[[3 1 2]
 [4 0 5]
 [6 7 8]]
------------
step: 5, move: left
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 6, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.03161907196044922'

In [110]:
start=define_start('moderate/3x3_8', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[1 5 4]
 [3 7 2]
 [6 0 8]]
------------
step: 1, move: up
[[1 5 4]
 [3 0 2]
 [6 7 8]]
------------
step: 2, move: up
[[1 0 4]
 [3 5 2]
 [6 7 8]]
------------
step: 3, move: right
[[1 4 0]
 [3 5 2]
 [6 7 8]]
------------
step: 4, move: down
[[1 4 2]
 [3 5 0]
 [6 7 8]]
------------
step: 5, move: left
[[1 4 2]
 [3 0 5]
 [6 7 8]]
------------
step: 6, move: up
[[1 0 2]
 [3 4 5]
 [6 7 8]]
------------
step: 7, move: left
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.02392292022705078'

In [111]:
play.AStar()

step: 0, move: None
[[1 5 4]
 [3 7 2]
 [6 0 8]]
------------
step: 1, move: up
[[1 5 4]
 [3 0 2]
 [6 7 8]]
------------
step: 2, move: up
[[1 0 4]
 [3 5 2]
 [6 7 8]]
------------
step: 3, move: right
[[1 4 0]
 [3 5 2]
 [6 7 8]]
------------
step: 4, move: down
[[1 4 2]
 [3 5 0]
 [6 7 8]]
------------
step: 5, move: left
[[1 4 2]
 [3 0 5]
 [6 7 8]]
------------
step: 6, move: up
[[1 0 2]
 [3 4 5]
 [6 7 8]]
------------
step: 7, move: left
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.043244123458862305'

In [112]:
start=define_start('moderate/3x3_9', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[1 2 7]
 [3 8 4]
 [6 0 5]]
------------
step: 1, move: up
[[1 2 7]
 [3 0 4]
 [6 8 5]]
------------
step: 2, move: right
[[1 2 7]
 [3 4 0]
 [6 8 5]]
------------
step: 3, move: up
[[1 2 0]
 [3 4 7]
 [6 8 5]]
------------
step: 4, move: left
[[1 0 2]
 [3 4 7]
 [6 8 5]]
------------
step: 5, move: down
[[1 4 2]
 [3 0 7]
 [6 8 5]]
------------
step: 6, move: right
[[1 4 2]
 [3 7 0]
 [6 8 5]]
------------
step: 7, move: down
[[1 4 2]
 [3 7 5]
 [6 8 0]]
------------
step: 8, move: left
[[1 4 2]
 [3 7 5]
 [6 0 8]]
------------
step: 9, move: up
[[1 4 2]
 [3 0 5]
 [6 7 8]]
------------
step: 10, move: up
[[1 0 2]
 [3 4 5]
 [6 7 8]]
------------
step: 11, move: left
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.09453201293945312'

In [113]:
play.AStar()

step: 0, move: None
[[1 2 7]
 [3 8 4]
 [6 0 5]]
------------
step: 1, move: up
[[1 2 7]
 [3 0 4]
 [6 8 5]]
------------
step: 2, move: right
[[1 2 7]
 [3 4 0]
 [6 8 5]]
------------
step: 3, move: up
[[1 2 0]
 [3 4 7]
 [6 8 5]]
------------
step: 4, move: left
[[1 0 2]
 [3 4 7]
 [6 8 5]]
------------
step: 5, move: down
[[1 4 2]
 [3 0 7]
 [6 8 5]]
------------
step: 6, move: right
[[1 4 2]
 [3 7 0]
 [6 8 5]]
------------
step: 7, move: down
[[1 4 2]
 [3 7 5]
 [6 8 0]]
------------
step: 8, move: left
[[1 4 2]
 [3 7 5]
 [6 0 8]]
------------
step: 9, move: up
[[1 4 2]
 [3 0 5]
 [6 7 8]]
------------
step: 10, move: up
[[1 0 2]
 [3 4 5]
 [6 7 8]]
------------
step: 11, move: left
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.13726592063903809'

In [114]:
start=define_start('moderate/3x3_10', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[0 3 1]
 [4 8 2]
 [6 5 7]]
------------
step: 1, move: right
[[3 0 1]
 [4 8 2]
 [6 5 7]]
------------
step: 2, move: right
[[3 1 0]
 [4 8 2]
 [6 5 7]]
------------
step: 3, move: down
[[3 1 2]
 [4 8 0]
 [6 5 7]]
------------
step: 4, move: left
[[3 1 2]
 [4 0 8]
 [6 5 7]]
------------
step: 5, move: down
[[3 1 2]
 [4 5 8]
 [6 0 7]]
------------
step: 6, move: right
[[3 1 2]
 [4 5 8]
 [6 7 0]]
------------
step: 7, move: up
[[3 1 2]
 [4 5 0]
 [6 7 8]]
------------
step: 8, move: left
[[3 1 2]
 [4 0 5]
 [6 7 8]]
------------
step: 9, move: left
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 10, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.06727099418640137'

In [115]:
play.AStar()

step: 0, move: None
[[0 3 1]
 [4 8 2]
 [6 5 7]]
------------
step: 1, move: right
[[3 0 1]
 [4 8 2]
 [6 5 7]]
------------
step: 2, move: right
[[3 1 0]
 [4 8 2]
 [6 5 7]]
------------
step: 3, move: down
[[3 1 2]
 [4 8 0]
 [6 5 7]]
------------
step: 4, move: left
[[3 1 2]
 [4 0 8]
 [6 5 7]]
------------
step: 5, move: down
[[3 1 2]
 [4 5 8]
 [6 0 7]]
------------
step: 6, move: right
[[3 1 2]
 [4 5 8]
 [6 7 0]]
------------
step: 7, move: up
[[3 1 2]
 [4 5 0]
 [6 7 8]]
------------
step: 8, move: left
[[3 1 2]
 [4 0 5]
 [6 7 8]]
------------
step: 9, move: left
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 10, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.07459402084350586'

# Difficult

In [116]:
start=define_start('difficult/3x3_1', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[5 3 2]
 [1 7 8]
 [6 0 4]]
------------
step: 1, move: up
[[5 3 2]
 [1 0 8]
 [6 7 4]]
------------
step: 2, move: left
[[5 3 2]
 [0 1 8]
 [6 7 4]]
------------
step: 3, move: up
[[0 3 2]
 [5 1 8]
 [6 7 4]]
------------
step: 4, move: right
[[3 0 2]
 [5 1 8]
 [6 7 4]]
------------
step: 5, move: down
[[3 1 2]
 [5 0 8]
 [6 7 4]]
------------
step: 6, move: left
[[3 1 2]
 [0 5 8]
 [6 7 4]]
------------
step: 7, move: down
[[3 1 2]
 [6 5 8]
 [0 7 4]]
------------
step: 8, move: right
[[3 1 2]
 [6 5 8]
 [7 0 4]]
------------
step: 9, move: right
[[3 1 2]
 [6 5 8]
 [7 4 0]]
------------
step: 10, move: up
[[3 1 2]
 [6 5 0]
 [7 4 8]]
------------
step: 11, move: left
[[3 1 2]
 [6 0 5]
 [7 4 8]]
------------
step: 12, move: down
[[3 1 2]
 [6 4 5]
 [7 0 8]]
------------
step: 13, move: left
[[3 1 2]
 [6 4 5]
 [0 7 8]]
------------
step: 14, move: up
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 15, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.3937869071960449'

In [117]:
play.AStar()

step: 0, move: None
[[5 3 2]
 [1 7 8]
 [6 0 4]]
------------
step: 1, move: up
[[5 3 2]
 [1 0 8]
 [6 7 4]]
------------
step: 2, move: left
[[5 3 2]
 [0 1 8]
 [6 7 4]]
------------
step: 3, move: up
[[0 3 2]
 [5 1 8]
 [6 7 4]]
------------
step: 4, move: right
[[3 0 2]
 [5 1 8]
 [6 7 4]]
------------
step: 5, move: down
[[3 1 2]
 [5 0 8]
 [6 7 4]]
------------
step: 6, move: left
[[3 1 2]
 [0 5 8]
 [6 7 4]]
------------
step: 7, move: down
[[3 1 2]
 [6 5 8]
 [0 7 4]]
------------
step: 8, move: right
[[3 1 2]
 [6 5 8]
 [7 0 4]]
------------
step: 9, move: right
[[3 1 2]
 [6 5 8]
 [7 4 0]]
------------
step: 10, move: up
[[3 1 2]
 [6 5 0]
 [7 4 8]]
------------
step: 11, move: left
[[3 1 2]
 [6 0 5]
 [7 4 8]]
------------
step: 12, move: down
[[3 1 2]
 [6 4 5]
 [7 0 8]]
------------
step: 13, move: left
[[3 1 2]
 [6 4 5]
 [0 7 8]]
------------
step: 14, move: up
[[3 1 2]
 [0 4 5]
 [6 7 8]]
------------
step: 15, move: up
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------


'Time:0.8606462478637695'

In [118]:
start=define_start('difficult/3x3_2', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[1 3 8]
 [7 6 0]
 [2 5 4]]
------------
step: 1, move: up
[[1 3 0]
 [7 6 8]
 [2 5 4]]
------------
step: 2, move: left
[[1 0 3]
 [7 6 8]
 [2 5 4]]
------------
step: 3, move: down
[[1 6 3]
 [7 0 8]
 [2 5 4]]
------------
step: 4, move: down
[[1 6 3]
 [7 5 8]
 [2 0 4]]
------------
step: 5, move: left
[[1 6 3]
 [7 5 8]
 [0 2 4]]
------------
step: 6, move: up
[[1 6 3]
 [0 5 8]
 [7 2 4]]
------------
step: 7, move: up
[[0 6 3]
 [1 5 8]
 [7 2 4]]
------------
step: 8, move: right
[[6 0 3]
 [1 5 8]
 [7 2 4]]
------------
step: 9, move: down
[[6 5 3]
 [1 0 8]
 [7 2 4]]
------------
step: 10, move: down
[[6 5 3]
 [1 2 8]
 [7 0 4]]
------------
step: 11, move: right
[[6 5 3]
 [1 2 8]
 [7 4 0]]
------------
step: 12, move: up
[[6 5 3]
 [1 2 0]
 [7 4 8]]
------------
step: 13, move: left
[[6 5 3]
 [1 0 2]
 [7 4 8]]
------------
step: 14, move: up
[[6 0 3]
 [1 5 2]
 [7 4 8]]
------------
step: 15, move: right
[[6 3 0]
 [1 5 2]
 [7 4 8]]
------------
step: 16, move: down
[[6 

'Time:29.706522703170776'

In [119]:
play.AStar()

step: 0, move: None
[[1 3 8]
 [7 6 0]
 [2 5 4]]
------------
step: 1, move: up
[[1 3 0]
 [7 6 8]
 [2 5 4]]
------------
step: 2, move: left
[[1 0 3]
 [7 6 8]
 [2 5 4]]
------------
step: 3, move: down
[[1 6 3]
 [7 0 8]
 [2 5 4]]
------------
step: 4, move: down
[[1 6 3]
 [7 5 8]
 [2 0 4]]
------------
step: 5, move: left
[[1 6 3]
 [7 5 8]
 [0 2 4]]
------------
step: 6, move: up
[[1 6 3]
 [0 5 8]
 [7 2 4]]
------------
step: 7, move: right
[[1 6 3]
 [5 0 8]
 [7 2 4]]
------------
step: 8, move: down
[[1 6 3]
 [5 2 8]
 [7 0 4]]
------------
step: 9, move: right
[[1 6 3]
 [5 2 8]
 [7 4 0]]
------------
step: 10, move: up
[[1 6 3]
 [5 2 0]
 [7 4 8]]
------------
step: 11, move: left
[[1 6 3]
 [5 0 2]
 [7 4 8]]
------------
step: 12, move: left
[[1 6 3]
 [0 5 2]
 [7 4 8]]
------------
step: 13, move: up
[[0 6 3]
 [1 5 2]
 [7 4 8]]
------------
step: 14, move: right
[[6 0 3]
 [1 5 2]
 [7 4 8]]
------------
step: 15, move: right
[[6 3 0]
 [1 5 2]
 [7 4 8]]
------------
step: 16, move: down
[

'Time:37.10054588317871'

In [120]:
start=define_start('difficult/3x3_3', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[7 6 4]
 [5 1 8]
 [0 3 2]]
------------
step: 1, move: up
[[7 6 4]
 [0 1 8]
 [5 3 2]]
------------
step: 2, move: right
[[7 6 4]
 [1 0 8]
 [5 3 2]]
------------
step: 3, move: up
[[7 0 4]
 [1 6 8]
 [5 3 2]]
------------
step: 4, move: left
[[0 7 4]
 [1 6 8]
 [5 3 2]]
------------
step: 5, move: down
[[1 7 4]
 [0 6 8]
 [5 3 2]]
------------
step: 6, move: right
[[1 7 4]
 [6 0 8]
 [5 3 2]]
------------
step: 7, move: down
[[1 7 4]
 [6 3 8]
 [5 0 2]]
------------
step: 8, move: left
[[1 7 4]
 [6 3 8]
 [0 5 2]]
------------
step: 9, move: up
[[1 7 4]
 [0 3 8]
 [6 5 2]]
------------
step: 10, move: right
[[1 7 4]
 [3 0 8]
 [6 5 2]]
------------
step: 11, move: right
[[1 7 4]
 [3 8 0]
 [6 5 2]]
------------
step: 12, move: down
[[1 7 4]
 [3 8 2]
 [6 5 0]]
------------
step: 13, move: left
[[1 7 4]
 [3 8 2]
 [6 0 5]]
------------
step: 14, move: up
[[1 7 4]
 [3 0 2]
 [6 8 5]]
------------
step: 15, move: up
[[1 0 4]
 [3 7 2]
 [6 8 5]]
------------
step: 16, move: right
[[

'Time:11.25679087638855'

In [121]:
play.AStar()

step: 0, move: None
[[7 6 4]
 [5 1 8]
 [0 3 2]]
------------
step: 1, move: up
[[7 6 4]
 [0 1 8]
 [5 3 2]]
------------
step: 2, move: right
[[7 6 4]
 [1 0 8]
 [5 3 2]]
------------
step: 3, move: up
[[7 0 4]
 [1 6 8]
 [5 3 2]]
------------
step: 4, move: left
[[0 7 4]
 [1 6 8]
 [5 3 2]]
------------
step: 5, move: down
[[1 7 4]
 [0 6 8]
 [5 3 2]]
------------
step: 6, move: right
[[1 7 4]
 [6 0 8]
 [5 3 2]]
------------
step: 7, move: down
[[1 7 4]
 [6 3 8]
 [5 0 2]]
------------
step: 8, move: left
[[1 7 4]
 [6 3 8]
 [0 5 2]]
------------
step: 9, move: up
[[1 7 4]
 [0 3 8]
 [6 5 2]]
------------
step: 10, move: right
[[1 7 4]
 [3 0 8]
 [6 5 2]]
------------
step: 11, move: right
[[1 7 4]
 [3 8 0]
 [6 5 2]]
------------
step: 12, move: down
[[1 7 4]
 [3 8 2]
 [6 5 0]]
------------
step: 13, move: left
[[1 7 4]
 [3 8 2]
 [6 0 5]]
------------
step: 14, move: up
[[1 7 4]
 [3 0 2]
 [6 8 5]]
------------
step: 15, move: up
[[1 0 4]
 [3 7 2]
 [6 8 5]]
------------
step: 16, move: right
[[

'Time:17.147642135620117'

In [122]:
start=define_start('difficult/3x3_4', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[7 8 6]
 [5 3 1]
 [4 0 2]]
------------
step: 1, move: up
[[7 8 6]
 [5 0 1]
 [4 3 2]]
------------
step: 2, move: left
[[7 8 6]
 [0 5 1]
 [4 3 2]]
------------
step: 3, move: down
[[7 8 6]
 [4 5 1]
 [0 3 2]]
------------
step: 4, move: right
[[7 8 6]
 [4 5 1]
 [3 0 2]]
------------
step: 5, move: up
[[7 8 6]
 [4 0 1]
 [3 5 2]]
------------
step: 6, move: up
[[7 0 6]
 [4 8 1]
 [3 5 2]]
------------
step: 7, move: right
[[7 6 0]
 [4 8 1]
 [3 5 2]]
------------
step: 8, move: down
[[7 6 1]
 [4 8 0]
 [3 5 2]]
------------
step: 9, move: down
[[7 6 1]
 [4 8 2]
 [3 5 0]]
------------
step: 10, move: left
[[7 6 1]
 [4 8 2]
 [3 0 5]]
------------
step: 11, move: up
[[7 6 1]
 [4 0 2]
 [3 8 5]]
------------
step: 12, move: up
[[7 0 1]
 [4 6 2]
 [3 8 5]]
------------
step: 13, move: right
[[7 1 0]
 [4 6 2]
 [3 8 5]]
------------
step: 14, move: down
[[7 1 2]
 [4 6 0]
 [3 8 5]]
------------
step: 15, move: down
[[7 1 2]
 [4 6 5]
 [3 8 0]]
------------
step: 16, move: left
[[7 

'Time:36.03764820098877'

In [123]:
play.AStar()

step: 0, move: None
[[7 8 6]
 [5 3 1]
 [4 0 2]]
------------
step: 1, move: right
[[7 8 6]
 [5 3 1]
 [4 2 0]]
------------
step: 2, move: up
[[7 8 6]
 [5 3 0]
 [4 2 1]]
------------
step: 3, move: up
[[7 8 0]
 [5 3 6]
 [4 2 1]]
------------
step: 4, move: left
[[7 0 8]
 [5 3 6]
 [4 2 1]]
------------
step: 5, move: down
[[7 3 8]
 [5 0 6]
 [4 2 1]]
------------
step: 6, move: left
[[7 3 8]
 [0 5 6]
 [4 2 1]]
------------
step: 7, move: up
[[0 3 8]
 [7 5 6]
 [4 2 1]]
------------
step: 8, move: right
[[3 0 8]
 [7 5 6]
 [4 2 1]]
------------
step: 9, move: down
[[3 5 8]
 [7 0 6]
 [4 2 1]]
------------
step: 10, move: down
[[3 5 8]
 [7 2 6]
 [4 0 1]]
------------
step: 11, move: right
[[3 5 8]
 [7 2 6]
 [4 1 0]]
------------
step: 12, move: up
[[3 5 8]
 [7 2 0]
 [4 1 6]]
------------
step: 13, move: up
[[3 5 0]
 [7 2 8]
 [4 1 6]]
------------
step: 14, move: left
[[3 0 5]
 [7 2 8]
 [4 1 6]]
------------
step: 15, move: down
[[3 2 5]
 [7 0 8]
 [4 1 6]]
------------
step: 16, move: down
[[3 

'Time:49.123027086257935'

In [124]:
start=define_start('difficult/3x3_5', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[2 4 8]
 [1 5 0]
 [7 6 3]]
------------
step: 1, move: up
[[2 4 0]
 [1 5 8]
 [7 6 3]]
------------
step: 2, move: left
[[2 0 4]
 [1 5 8]
 [7 6 3]]
------------
step: 3, move: down
[[2 5 4]
 [1 0 8]
 [7 6 3]]
------------
step: 4, move: down
[[2 5 4]
 [1 6 8]
 [7 0 3]]
------------
step: 5, move: right
[[2 5 4]
 [1 6 8]
 [7 3 0]]
------------
step: 6, move: up
[[2 5 4]
 [1 6 0]
 [7 3 8]]
------------
step: 7, move: up
[[2 5 0]
 [1 6 4]
 [7 3 8]]
------------
step: 8, move: left
[[2 0 5]
 [1 6 4]
 [7 3 8]]
------------
step: 9, move: left
[[0 2 5]
 [1 6 4]
 [7 3 8]]
------------
step: 10, move: down
[[1 2 5]
 [0 6 4]
 [7 3 8]]
------------
step: 11, move: right
[[1 2 5]
 [6 0 4]
 [7 3 8]]
------------
step: 12, move: down
[[1 2 5]
 [6 3 4]
 [7 0 8]]
------------
step: 13, move: left
[[1 2 5]
 [6 3 4]
 [0 7 8]]
------------
step: 14, move: up
[[1 2 5]
 [0 3 4]
 [6 7 8]]
------------
step: 15, move: right
[[1 2 5]
 [3 0 4]
 [6 7 8]]
------------
step: 16, move: right
[

'Time:2.748668909072876'

In [125]:
play.AStar()

step: 0, move: None
[[2 4 8]
 [1 5 0]
 [7 6 3]]
------------
step: 1, move: up
[[2 4 0]
 [1 5 8]
 [7 6 3]]
------------
step: 2, move: left
[[2 0 4]
 [1 5 8]
 [7 6 3]]
------------
step: 3, move: down
[[2 5 4]
 [1 0 8]
 [7 6 3]]
------------
step: 4, move: down
[[2 5 4]
 [1 6 8]
 [7 0 3]]
------------
step: 5, move: right
[[2 5 4]
 [1 6 8]
 [7 3 0]]
------------
step: 6, move: up
[[2 5 4]
 [1 6 0]
 [7 3 8]]
------------
step: 7, move: up
[[2 5 0]
 [1 6 4]
 [7 3 8]]
------------
step: 8, move: left
[[2 0 5]
 [1 6 4]
 [7 3 8]]
------------
step: 9, move: left
[[0 2 5]
 [1 6 4]
 [7 3 8]]
------------
step: 10, move: down
[[1 2 5]
 [0 6 4]
 [7 3 8]]
------------
step: 11, move: right
[[1 2 5]
 [6 0 4]
 [7 3 8]]
------------
step: 12, move: down
[[1 2 5]
 [6 3 4]
 [7 0 8]]
------------
step: 13, move: left
[[1 2 5]
 [6 3 4]
 [0 7 8]]
------------
step: 14, move: up
[[1 2 5]
 [0 3 4]
 [6 7 8]]
------------
step: 15, move: right
[[1 2 5]
 [3 0 4]
 [6 7 8]]
------------
step: 16, move: right
[

'Time:4.346288681030273'

In [126]:
start=define_start('difficult/3x3_6', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[2 1 8]
 [4 0 5]
 [6 7 3]]
------------
step: 1, move: up
[[2 0 8]
 [4 1 5]
 [6 7 3]]
------------
step: 2, move: left
[[0 2 8]
 [4 1 5]
 [6 7 3]]
------------
step: 3, move: down
[[4 2 8]
 [0 1 5]
 [6 7 3]]
------------
step: 4, move: right
[[4 2 8]
 [1 0 5]
 [6 7 3]]
------------
step: 5, move: right
[[4 2 8]
 [1 5 0]
 [6 7 3]]
------------
step: 6, move: up
[[4 2 0]
 [1 5 8]
 [6 7 3]]
------------
step: 7, move: left
[[4 0 2]
 [1 5 8]
 [6 7 3]]
------------
step: 8, move: left
[[0 4 2]
 [1 5 8]
 [6 7 3]]
------------
step: 9, move: down
[[1 4 2]
 [0 5 8]
 [6 7 3]]
------------
step: 10, move: down
[[1 4 2]
 [6 5 8]
 [0 7 3]]
------------
step: 11, move: right
[[1 4 2]
 [6 5 8]
 [7 0 3]]
------------
step: 12, move: right
[[1 4 2]
 [6 5 8]
 [7 3 0]]
------------
step: 13, move: up
[[1 4 2]
 [6 5 0]
 [7 3 8]]
------------
step: 14, move: left
[[1 4 2]
 [6 0 5]
 [7 3 8]]
------------
step: 15, move: down
[[1 4 2]
 [6 3 5]
 [7 0 8]]
------------
step: 16, move: left

'Time:4.449663162231445'

In [127]:
play.AStar()

step: 0, move: None
[[2 1 8]
 [4 0 5]
 [6 7 3]]
------------
step: 1, move: right
[[2 1 8]
 [4 5 0]
 [6 7 3]]
------------
step: 2, move: down
[[2 1 8]
 [4 5 3]
 [6 7 0]]
------------
step: 3, move: left
[[2 1 8]
 [4 5 3]
 [6 0 7]]
------------
step: 4, move: up
[[2 1 8]
 [4 0 3]
 [6 5 7]]
------------
step: 5, move: up
[[2 0 8]
 [4 1 3]
 [6 5 7]]
------------
step: 6, move: left
[[0 2 8]
 [4 1 3]
 [6 5 7]]
------------
step: 7, move: down
[[4 2 8]
 [0 1 3]
 [6 5 7]]
------------
step: 8, move: right
[[4 2 8]
 [1 0 3]
 [6 5 7]]
------------
step: 9, move: right
[[4 2 8]
 [1 3 0]
 [6 5 7]]
------------
step: 10, move: up
[[4 2 0]
 [1 3 8]
 [6 5 7]]
------------
step: 11, move: left
[[4 0 2]
 [1 3 8]
 [6 5 7]]
------------
step: 12, move: left
[[0 4 2]
 [1 3 8]
 [6 5 7]]
------------
step: 13, move: down
[[1 4 2]
 [0 3 8]
 [6 5 7]]
------------
step: 14, move: right
[[1 4 2]
 [3 0 8]
 [6 5 7]]
------------
step: 15, move: down
[[1 4 2]
 [3 5 8]
 [6 0 7]]
------------
step: 16, move: righ

'Time:10.198416233062744'

In [128]:
start=define_start('difficult/3x3_7', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[2 5 4]
 [0 3 1]
 [6 8 7]]
------------
step: 1, move: right
[[2 5 4]
 [3 0 1]
 [6 8 7]]
------------
step: 2, move: right
[[2 5 4]
 [3 1 0]
 [6 8 7]]
------------
step: 3, move: down
[[2 5 4]
 [3 1 7]
 [6 8 0]]
------------
step: 4, move: left
[[2 5 4]
 [3 1 7]
 [6 0 8]]
------------
step: 5, move: left
[[2 5 4]
 [3 1 7]
 [0 6 8]]
------------
step: 6, move: up
[[2 5 4]
 [0 1 7]
 [3 6 8]]
------------
step: 7, move: right
[[2 5 4]
 [1 0 7]
 [3 6 8]]
------------
step: 8, move: right
[[2 5 4]
 [1 7 0]
 [3 6 8]]
------------
step: 9, move: up
[[2 5 0]
 [1 7 4]
 [3 6 8]]
------------
step: 10, move: left
[[2 0 5]
 [1 7 4]
 [3 6 8]]
------------
step: 11, move: left
[[0 2 5]
 [1 7 4]
 [3 6 8]]
------------
step: 12, move: down
[[1 2 5]
 [0 7 4]
 [3 6 8]]
------------
step: 13, move: down
[[1 2 5]
 [3 7 4]
 [0 6 8]]
------------
step: 14, move: right
[[1 2 5]
 [3 7 4]
 [6 0 8]]
------------
step: 15, move: up
[[1 2 5]
 [3 0 4]
 [6 7 8]]
------------
step: 16, move: rig

'Time:3.9613449573516846'

In [129]:
play.AStar()

step: 0, move: None
[[2 5 4]
 [0 3 1]
 [6 8 7]]
------------
step: 1, move: right
[[2 5 4]
 [3 0 1]
 [6 8 7]]
------------
step: 2, move: right
[[2 5 4]
 [3 1 0]
 [6 8 7]]
------------
step: 3, move: down
[[2 5 4]
 [3 1 7]
 [6 8 0]]
------------
step: 4, move: left
[[2 5 4]
 [3 1 7]
 [6 0 8]]
------------
step: 5, move: left
[[2 5 4]
 [3 1 7]
 [0 6 8]]
------------
step: 6, move: up
[[2 5 4]
 [0 1 7]
 [3 6 8]]
------------
step: 7, move: right
[[2 5 4]
 [1 0 7]
 [3 6 8]]
------------
step: 8, move: right
[[2 5 4]
 [1 7 0]
 [3 6 8]]
------------
step: 9, move: up
[[2 5 0]
 [1 7 4]
 [3 6 8]]
------------
step: 10, move: left
[[2 0 5]
 [1 7 4]
 [3 6 8]]
------------
step: 11, move: left
[[0 2 5]
 [1 7 4]
 [3 6 8]]
------------
step: 12, move: down
[[1 2 5]
 [0 7 4]
 [3 6 8]]
------------
step: 13, move: down
[[1 2 5]
 [3 7 4]
 [0 6 8]]
------------
step: 14, move: right
[[1 2 5]
 [3 7 4]
 [6 0 8]]
------------
step: 15, move: up
[[1 2 5]
 [3 0 4]
 [6 7 8]]
------------
step: 16, move: rig

'Time:6.773504972457886'

In [130]:
start=define_start('difficult/3x3_8', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[6 4 1]
 [7 2 0]
 [8 5 3]]
------------
step: 1, move: left
[[6 4 1]
 [7 0 2]
 [8 5 3]]
------------
step: 2, move: up
[[6 0 1]
 [7 4 2]
 [8 5 3]]
------------
step: 3, move: right
[[6 1 0]
 [7 4 2]
 [8 5 3]]
------------
step: 4, move: down
[[6 1 2]
 [7 4 0]
 [8 5 3]]
------------
step: 5, move: down
[[6 1 2]
 [7 4 3]
 [8 5 0]]
------------
step: 6, move: left
[[6 1 2]
 [7 4 3]
 [8 0 5]]
------------
step: 7, move: left
[[6 1 2]
 [7 4 3]
 [0 8 5]]
------------
step: 8, move: up
[[6 1 2]
 [0 4 3]
 [7 8 5]]
------------
step: 9, move: up
[[0 1 2]
 [6 4 3]
 [7 8 5]]
------------
step: 10, move: right
[[1 0 2]
 [6 4 3]
 [7 8 5]]
------------
step: 11, move: down
[[1 4 2]
 [6 0 3]
 [7 8 5]]
------------
step: 12, move: right
[[1 4 2]
 [6 3 0]
 [7 8 5]]
------------
step: 13, move: down
[[1 4 2]
 [6 3 5]
 [7 8 0]]
------------
step: 14, move: left
[[1 4 2]
 [6 3 5]
 [7 0 8]]
------------
step: 15, move: left
[[1 4 2]
 [6 3 5]
 [0 7 8]]
------------
step: 16, move: up
[[

'Time:2.953460931777954'

In [131]:
play.AStar()

step: 0, move: None
[[6 4 1]
 [7 2 0]
 [8 5 3]]
------------
step: 1, move: left
[[6 4 1]
 [7 0 2]
 [8 5 3]]
------------
step: 2, move: up
[[6 0 1]
 [7 4 2]
 [8 5 3]]
------------
step: 3, move: right
[[6 1 0]
 [7 4 2]
 [8 5 3]]
------------
step: 4, move: down
[[6 1 2]
 [7 4 0]
 [8 5 3]]
------------
step: 5, move: down
[[6 1 2]
 [7 4 3]
 [8 5 0]]
------------
step: 6, move: left
[[6 1 2]
 [7 4 3]
 [8 0 5]]
------------
step: 7, move: left
[[6 1 2]
 [7 4 3]
 [0 8 5]]
------------
step: 8, move: up
[[6 1 2]
 [0 4 3]
 [7 8 5]]
------------
step: 9, move: up
[[0 1 2]
 [6 4 3]
 [7 8 5]]
------------
step: 10, move: right
[[1 0 2]
 [6 4 3]
 [7 8 5]]
------------
step: 11, move: down
[[1 4 2]
 [6 0 3]
 [7 8 5]]
------------
step: 12, move: right
[[1 4 2]
 [6 3 0]
 [7 8 5]]
------------
step: 13, move: down
[[1 4 2]
 [6 3 5]
 [7 8 0]]
------------
step: 14, move: left
[[1 4 2]
 [6 3 5]
 [7 0 8]]
------------
step: 15, move: left
[[1 4 2]
 [6 3 5]
 [0 7 8]]
------------
step: 16, move: up
[[

'Time:5.31724214553833'

In [132]:
start=define_start('difficult/3x3_9', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[8 2 0]
 [1 6 5]
 [4 3 7]]
------------
step: 1, move: left
[[8 0 2]
 [1 6 5]
 [4 3 7]]
------------
step: 2, move: left
[[0 8 2]
 [1 6 5]
 [4 3 7]]
------------
step: 3, move: down
[[1 8 2]
 [0 6 5]
 [4 3 7]]
------------
step: 4, move: down
[[1 8 2]
 [4 6 5]
 [0 3 7]]
------------
step: 5, move: right
[[1 8 2]
 [4 6 5]
 [3 0 7]]
------------
step: 6, move: up
[[1 8 2]
 [4 0 5]
 [3 6 7]]
------------
step: 7, move: up
[[1 0 2]
 [4 8 5]
 [3 6 7]]
------------
step: 8, move: right
[[1 2 0]
 [4 8 5]
 [3 6 7]]
------------
step: 9, move: down
[[1 2 5]
 [4 8 0]
 [3 6 7]]
------------
step: 10, move: left
[[1 2 5]
 [4 0 8]
 [3 6 7]]
------------
step: 11, move: left
[[1 2 5]
 [0 4 8]
 [3 6 7]]
------------
step: 12, move: down
[[1 2 5]
 [3 4 8]
 [0 6 7]]
------------
step: 13, move: right
[[1 2 5]
 [3 4 8]
 [6 0 7]]
------------
step: 14, move: right
[[1 2 5]
 [3 4 8]
 [6 7 0]]
------------
step: 15, move: up
[[1 2 5]
 [3 4 0]
 [6 7 8]]
------------
step: 16, move: up
[

'Time:1.3650600910186768'

In [133]:
play.AStar()

step: 0, move: None
[[8 2 0]
 [1 6 5]
 [4 3 7]]
------------
step: 1, move: left
[[8 0 2]
 [1 6 5]
 [4 3 7]]
------------
step: 2, move: left
[[0 8 2]
 [1 6 5]
 [4 3 7]]
------------
step: 3, move: down
[[1 8 2]
 [0 6 5]
 [4 3 7]]
------------
step: 4, move: down
[[1 8 2]
 [4 6 5]
 [0 3 7]]
------------
step: 5, move: right
[[1 8 2]
 [4 6 5]
 [3 0 7]]
------------
step: 6, move: up
[[1 8 2]
 [4 0 5]
 [3 6 7]]
------------
step: 7, move: up
[[1 0 2]
 [4 8 5]
 [3 6 7]]
------------
step: 8, move: right
[[1 2 0]
 [4 8 5]
 [3 6 7]]
------------
step: 9, move: down
[[1 2 5]
 [4 8 0]
 [3 6 7]]
------------
step: 10, move: left
[[1 2 5]
 [4 0 8]
 [3 6 7]]
------------
step: 11, move: left
[[1 2 5]
 [0 4 8]
 [3 6 7]]
------------
step: 12, move: down
[[1 2 5]
 [3 4 8]
 [0 6 7]]
------------
step: 13, move: right
[[1 2 5]
 [3 4 8]
 [6 0 7]]
------------
step: 14, move: right
[[1 2 5]
 [3 4 8]
 [6 7 0]]
------------
step: 15, move: up
[[1 2 5]
 [3 4 0]
 [6 7 8]]
------------
step: 16, move: up
[

'Time:4.990365028381348'

In [134]:
start=define_start('difficult/3x3_10', 3)
play=Game(board=start, parent=None, path=0, N=3, move=None)
play.bfs()

step: 0, move: None
[[5 4 8]
 [7 0 6]
 [2 1 3]]
------------
step: 1, move: left
[[5 4 8]
 [0 7 6]
 [2 1 3]]
------------
step: 2, move: down
[[5 4 8]
 [2 7 6]
 [0 1 3]]
------------
step: 3, move: right
[[5 4 8]
 [2 7 6]
 [1 0 3]]
------------
step: 4, move: right
[[5 4 8]
 [2 7 6]
 [1 3 0]]
------------
step: 5, move: up
[[5 4 8]
 [2 7 0]
 [1 3 6]]
------------
step: 6, move: up
[[5 4 0]
 [2 7 8]
 [1 3 6]]
------------
step: 7, move: left
[[5 0 4]
 [2 7 8]
 [1 3 6]]
------------
step: 8, move: left
[[0 5 4]
 [2 7 8]
 [1 3 6]]
------------
step: 9, move: down
[[2 5 4]
 [0 7 8]
 [1 3 6]]
------------
step: 10, move: down
[[2 5 4]
 [1 7 8]
 [0 3 6]]
------------
step: 11, move: right
[[2 5 4]
 [1 7 8]
 [3 0 6]]
------------
step: 12, move: right
[[2 5 4]
 [1 7 8]
 [3 6 0]]
------------
step: 13, move: up
[[2 5 4]
 [1 7 0]
 [3 6 8]]
------------
step: 14, move: up
[[2 5 0]
 [1 7 4]
 [3 6 8]]
------------
step: 15, move: left
[[2 0 5]
 [1 7 4]
 [3 6 8]]
------------
step: 16, move: left
[

'Time:23.052996158599854'

In [135]:
play.AStar()

step: 0, move: None
[[5 4 8]
 [7 0 6]
 [2 1 3]]
------------
step: 1, move: down
[[5 4 8]
 [7 1 6]
 [2 0 3]]
------------
step: 2, move: left
[[5 4 8]
 [7 1 6]
 [0 2 3]]
------------
step: 3, move: up
[[5 4 8]
 [0 1 6]
 [7 2 3]]
------------
step: 4, move: right
[[5 4 8]
 [1 0 6]
 [7 2 3]]
------------
step: 5, move: right
[[5 4 8]
 [1 6 0]
 [7 2 3]]
------------
step: 6, move: up
[[5 4 0]
 [1 6 8]
 [7 2 3]]
------------
step: 7, move: left
[[5 0 4]
 [1 6 8]
 [7 2 3]]
------------
step: 8, move: left
[[0 5 4]
 [1 6 8]
 [7 2 3]]
------------
step: 9, move: down
[[1 5 4]
 [0 6 8]
 [7 2 3]]
------------
step: 10, move: right
[[1 5 4]
 [6 0 8]
 [7 2 3]]
------------
step: 11, move: down
[[1 5 4]
 [6 2 8]
 [7 0 3]]
------------
step: 12, move: right
[[1 5 4]
 [6 2 8]
 [7 3 0]]
------------
step: 13, move: up
[[1 5 4]
 [6 2 0]
 [7 3 8]]
------------
step: 14, move: up
[[1 5 0]
 [6 2 4]
 [7 3 8]]
------------
step: 15, move: left
[[1 0 5]
 [6 2 4]
 [7 3 8]]
------------
step: 16, move: down
[

'Time:30.4260311126709'

# Extreme

The game was not solved within a minute with either breadth first search or A Star. I tried to let them go for a few minutes, but the games were not solved. 

In [140]:
# start=define_start('extreme/3x3_2', 4)
# play=Game(board=start, parent=None, path=0, N=4, move=None)
# play.bfs()

In [141]:
# play.AStar()